### ISSUE TITLE
Option "Zminsfr": how to properly set its value?

### ISSUE THREAD

**Issue by liweitianux** [mariogrs/Simfast21#16]
Dear Dr. Santos,

There is the option ``Zminsfr`` in the configuration file ``simfast21.ini``, and it has the default value of 12.0, which is between ``zmax`` and ``zmin``.  But how does its value affect the simulation results?

Currently I'm interested in a frequency range of, say 154 - 164 MHz, which corresponds to redshift range from about 8.22 - 7.77 .  Therefore, can I just set these in the configuration file?

```
zmax = 8.5
zmin = 7.5
dz = 0.05
```

Should these settings be fine?  If it is OK, then how to set an appropriate value for ``Zminsfr``?  Or the Lya + Xray effects can be just disabled?

Thank you!
Aly

**Comment by mariogrs** [comment]
Zminsfr is the minimum redshift down to which the simulation calculates the SFRD and all the spin temperature stuff. Below that it just assumes T_S>>TCMB and there is no need to generate the SFR boxes. I've added an explanation to simfast21.ini.
Note that for zmax = 8.5 you should be fine assuming TS>>TCMB unless you have some very strange model. So you can set use_Lya_xrays = F

**Comment by liweitianux** [comment]
Dear @mariogrs ,

Thank you for the quick explanation.  And the added comments make the related options much more clear.

Several days ago (before your recent significant code updates), I tried to simulate the 21 cm signal brightness temperatures within redshift range 7.5 - 8.5, but I forget to change ``Zminsfr`` which had the default value of 7.0 (< ``zmin=7.5`` in this case), and then the simulation **failed** due to the missing SFR cubes at those lower redshifts (I think the newly added option ``use_SFR=F`` was default to ``T`` for the old codes).

Maybe it is good to first validate the loaded configurations before doing actual simulation?  Just a little suggestion.

Best regards,
Aly

**Comment by mariogrs** [comment]
That's a good point. I just added some basic checks. Will add more later...
