### ISSUE TITLE
release request

### ISSUE THREAD

**Issue by gijzelaerr** [mariogrs/Simfast21#7]
hi!

It has been requested that this software becomes part of the KERN suite:

http://kernsuite.info

see packaging discussion here:

kernsuite/packaging#21

For this I will try to make a package of this software. Can you maybe press the 'make release' button? That would simplify my packaging life.

Thanks!

**Comment by mariogrs** [comment]
Sure. Note that I am currently upgrading the code.

**Comment by mariogrs** [comment]
ps: you shouldn't include 21cmFAST - it is the competition - you guys
should promote our software...

**Comment by gijzelaerr** [comment]
even better, make a release before you upgrade the code

**Comment by mariogrs** [comment]
done. it is a working version anyway.

**Comment by gijzelaerr** [comment]
awesome
